# 	Milo Zak
#	Z1917365
#	CSCI340-3
#
#	I certify that this is my own work and where appropriate an extension
#	of the starter code provided for the assignment.

CXX = g++
CXXFLAGS = -std=c++11 -Wall -Werror -g

all: introduction

introduction: introduction.o
	g++ $(CXXFLAGS) -o introduction $^

introduction.o: introduction.cc

clean:
	rm -f introduction test *.o



